### ISSUE TITLE
go mod tidy error

### ISSUE THREAD

**Issue by daysleep666** [ks3sdklib/aws-sdk-go#13]
go mod tidy
go: finding github.com/ks3sdklib/aws-sdk-go latest
git.xxxxxx.com/xxx/osc/pkg/s3/ksyun imports
        github.com/ks3sdklib/aws-sdk-go/aws tested by
        github.com/ks3sdklib/aws-sdk-go/aws.test imports
        github.com/ks3sdklib/aws-sdk-go/service/dynamodb: module github.com/ks3sdklib/aws-sdk-go@latest found (v0.0.0-20191128113133-b330986da295), but does not contain package github.com/ks3sdklib/aws-sdk-go/service/dynamodb

**Comment by ColeZhangc** [comment]
go mod tidy 
go: finding module for package github.com/ks3sdklib/aws-sdk-go/service/dynamodb
xx  imports
        github.com/ks3sdklib/aws-sdk-go/aws tested by
        github.com/ks3sdklib/aws-sdk-go/aws.test imports
        github.com/ks3sdklib/aws-sdk-go/service/dynamodb: module github.com/ks3sdklib/aws-sdk-go@latest found (v0.0.1), but does not contain package github.com/ks3sdklib/aws-sdk-go/service/dynamodb
