### ISSUE TITLE
input.isReTurnResults 始终为nil。删除文件会触发panic 

### ISSUE THREAD

**Issue by daelephant** [ks3sdklib/aws-sdk-go#18]
// This operation enables you to delete multiple objects from a bucket using
// a single HTTP request. You may specify up to 1000 keys.
func (c *S3) DeleteObjects(input *DeleteObjectsInput) *DeleteObjectsOutput {
	var errors []*Error
	var okList []*DeletedObject
	for _, t := range input.Delete.Objects {
		_, err := c.DeleteObject(&DeleteObjectInput{Bucket: input.Bucket, Key: t.Key})
		if *input.isReTurnResults { //此处会panic
			if err != nil {
				aerr, _ := err.(awserr.Error)
				errors = append(errors, &Error{Key: t.Key, Code: aws.String(aerr.Code()), Message: aws.String(aerr.Message())})
			} else {
				okList = append(okList, &DeletedObject{Key: t.Key})
			}
		}
	}
	output := &DeleteObjectsOutput{
		Deleted: okList,
		Errors:  errors,
	}
	return output
}

**Comment by chenqichen** [comment]
现在使用的是什么version   之前修复了这个问题；
