### ISSUE TITLE
`S3` 没有实现 `S3API` 接口

### ISSUE THREAD

**Issue by lance6716** [ks3sdklib/aws-sdk-go#28]
https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/s3iface/interface.go#L38

https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/api.go#L428

少返回了一个 error

**Comment by 2540153480** [comment]
在S3API中，DeleteObjects是通过服务端批量删除实现的，KS3暂不支持该特性，因此该方法是通过多次调用DeleteObject实现的，可能会产生多个error，这些error信息都保存在了DeleteObjectsOutput中

**Comment by lance6716** [comment]
这里的诉求是 `S3` 没有实现 `S3API` 接口。如果不方便改函数签名的话能否修改 `S3API`？这个接口会被我们用来 mock 做单元测试

**Comment by 2540153480** [comment]
我们计划将：
https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/api.go#L428
修改为：
`func (c *S3) DeleteObjects(input *DeleteObjectsInput) (*DeleteObjectsOutput, error)`
从而保证返回值格式与其他函数保持一致（都拥有output和error两个返回值）
您看这样是否可以解决问题

**Comment by lance6716** [comment]
可以的，感谢
