### ISSUE TITLE
`s3.New` 不支持传入 `nil`

### ISSUE THREAD

**Issue by lance6716** [ks3sdklib/aws-sdk-go#30]
https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/service.go#L25

但是 SDK 其他地方有在使用

https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/s3manager/upload.go#L277

**Comment by 2540153480** [comment]
您好，该方法是有对nil的处理，这种情况会采用默认配置
https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/service.go#L25-L30
https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/aws/config.go#L90-L93

**Comment by lance6716** [comment]
在 34 行会 panic，可以写一个单元测试验证一下
https://github.com/ks3sdklib/aws-sdk-go/blob/0c0c392344318440d0ddf2f063d6b3eb588b6a4e/service/s3/service.go#L25-L34
